name: Tag, Release, and Publish Python Package

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Extract Version from TOML
        uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: 'pyproject.toml'
          field: 'project.version'
      - name: Print TOML Version
        run: |
          echo TOML Version: ${{ steps.read_toml.outputs.value }}

      - uses: mukunku/tag-exists-action@v1.4.0
        id: checkTag
        with:
          tag: v${{ steps.read_toml.outputs.value }}

      - name: If Tag does not exists, Create Git Tag
        if: steps.checkTag.outputs.exists == 'false'
        run: |
          git tag v${{ steps.read_toml.outputs.value }}
          git push origin v${{ steps.read_toml.outputs.value }}

      - name: Create GitHub Release
        if: steps.checkTag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.read_toml.outputs.value }}
          name: v${{ steps.read_toml.outputs.value }}
          generate_release_notes: true

  pypi-publish:
    needs: tag_and_release
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build distribution
        run: python -m build

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
